# Generated by Django 4.1.3 on 2023-01-20 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("electronics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingnetwork",
            name="stuff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Работники",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="contacts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics.contacts",
                verbose_name="Контакты",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics.products",
                verbose_name="Продукция",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="stuff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Работники",
            ),
        ),
        migrations.AddField(
            model_name="contacts",
            name="address",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="electronics.addresscompany",
                verbose_name="Адрес",
            ),
        ),
    ]
