# Generated by Django 4.1.3 on 2023-01-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tradingnetwork",
            options={"verbose_name": "Покупатель", "verbose_name_plural": "Покупатели"},
        ),
        migrations.AlterField(
            model_name="tradingnetwork",
            name="name_trade_network",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Розница"), (1, "Предприниматель")],
                verbose_name="Звено цепи",
            ),
        ),
    ]
