# Generated by Django 4.1.3 on 2023-01-21 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0003_alter_tradingnetwork_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingnetwork",
            name="name_trade_network",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Розница"), (2, "Предприниматель")],
                verbose_name="Звено цепи",
            ),
        ),
        migrations.AlterField(
            model_name="tradingnetwork",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"name_trade_network": 0},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics.provider",
                verbose_name="Поставщик",
            ),
        ),
    ]
