# Generated by Django 4.1.3 on 2023-01-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0003_alter_addresscompany_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="debt_currency",
        ),
        migrations.RemoveField(
            model_name="tradingnetwork",
            name="debt_currency",
        ),
        migrations.AlterField(
            model_name="provider",
            name="debt",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="tradingnetwork",
            name="debt",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
