# Generated by Django 4.1.3 on 2023-01-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0004_alter_tradingnetwork_name_trade_network_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingnetwork",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics.provider",
                verbose_name="Поставщик",
            ),
        ),
    ]
